### PR TITLE
Added option for saving all files before build

### PR DESCRIPTION
**Pull request by DjPale**
Not sure if this is the correct place / module, but it is a missing feature that I would really like to have.

### CODE REVIEW

**Comment by ruby0x1** [comment]
You can make the default true @DjPale

**Comment by ruby0x1** [comment]
I wasn't paying close attention previously, I wonder if this PR would make more sense on atom-haxe @jeremyfa

**Comment by jeremyfa** [comment]
Right, we should move the change to atom-haxe for next release (which will still work in pair with atom-flow anyway)

**Comment by jeremyfa** [comment]
@DjPale Can you make a PR to the atom-haxe repo with the same changes? I believe it can be done there: https://github.com/snowkit/atom-haxe/blob/999ad331161cc26041c980a969d536b7146039f8/lib/build/build.js#L11

**Comment by DjPale** [comment]
Ok, moved as per comments from @jeremyfa to https://github.com/snowkit/atom-haxe/pull/57

**Pull request closed without merging**
